#ifndef KOPE_G5_TEXTUREFORMAT_HEADER
#define KOPE_G5_TEXTUREFORMAT_HEADER

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum kope_g5_texture_format {
	KOPE_G5_TEXTURE_FORMAT_R8_UNORM,
	KOPE_G5_TEXTURE_FORMAT_R8_SNORM,
	KOPE_G5_TEXTURE_FORMAT_R8_UINT,
	KOPE_G5_TEXTURE_FORMAT_R8_SINT,
	KOPE_G5_TEXTURE_FORMAT_R16_UINT,
	KOPE_G5_TEXTURE_FORMAT_R16_SINT,
	KOPE_G5_TEXTURE_FORMAT_R16_FLOAT,
	KOPE_G5_TEXTURE_FORMAT_RG8_UNORM,
	KOPE_G5_TEXTURE_FORMAT_RG8_SNORM,
	KOPE_G5_TEXTURE_FORMAT_RG8_UINT,
	KOPE_G5_TEXTURE_FORMAT_RG8_SINT,
	KOPE_G5_TEXTURE_FORMAT_R32_UINT,
	KOPE_G5_TEXTURE_FORMAT_R32_SINT,
	KOPE_G5_TEXTURE_FORMAT_R32_FLOAT,
	KOPE_G5_TEXTURE_FORMAT_RG16_UINT,
	KOPE_G5_TEXTURE_FORMAT_RG16_SINT,
	KOPE_G5_TEXTURE_FORMAT_RG16_FLOAT,
	KOPE_G5_TEXTURE_FORMAT_RGBA8_UNORM,
	KOPE_G5_TEXTURE_FORMAT_RGBA8_UNORM_SRGB,
	KOPE_G5_TEXTURE_FORMAT_RGBA8_SNORM,
	KOPE_G5_TEXTURE_FORMAT_RGBA8_UINT,
	KOPE_G5_TEXTURE_FORMAT_RGBA8_SINT,
	KOPE_G5_TEXTURE_FORMAT_BGRA8_UNORM,
	KOPE_G5_TEXTURE_FORMAT_BGRA8_UNORM_SRGB,
	KOPE_G5_TEXTURE_FORMAT_RGB9E5U_FLOAT,
	KOPE_G5_TEXTURE_FORMAT_RGB10A2_UINT,
	KOPE_G5_TEXTURE_FORMAT_RGB10A2_UNORM,
	KOPE_G5_TEXTURE_FORMAT_RG11B10U_FLOAT,
	KOPE_G5_TEXTURE_FORMAT_RG32_UINT,
	KOPE_G5_TEXTURE_FORMAT_RG32_SINT,
	KOPE_G5_TEXTURE_FORMAT_RG32_FLOAT,
	KOPE_G5_TEXTURE_FORMAT_RGBA16_UINT,
	KOPE_G5_TEXTURE_FORMAT_RGBA16_SINT,
	KOPE_G5_TEXTURE_FORMAT_RGBA16_FLOAT,
	KOPE_G5_TEXTURE_FORMAT_RGBA32_UINT,
	KOPE_G5_TEXTURE_FORMAT_RGBA32_SINT,
	KOPE_G5_TEXTURE_FORMAT_RGBA32_FLOAT,
	// KOPE_G5_TEXTURE_FORMAT_STENCIL8, // not available in d3d12
	KOPE_G5_TEXTURE_FORMAT_DEPTH16_UNORM,
	KOPE_G5_TEXTURE_FORMAT_DEPTH24PLUS_NOTHING8,
	KOPE_G5_TEXTURE_FORMAT_DEPTH24PLUS_STENCIL8,
	KOPE_G5_TEXTURE_FORMAT_DEPTH32FLOAT,
	KOPE_G5_TEXTURE_FORMAT_DEPTH32FLOAT_STENCIL8_NOTHING24,
	// TODO: compressed formats
} kope_g5_texture_format;

uint32_t kope_g5_texture_format_byte_size(kope_g5_texture_format format);

bool kope_g5_texture_format_is_depth(kope_g5_texture_format format);

#ifdef __cplusplus
}
#endif

#endif
