#!/usr/bin/env bash

. `dirname "$0"`/Tools/platform.sh
if test -f "Tools/$KINC_PLATFORM/kmake"; then
git -C `dirname "$0"` submodule update --remote --merge "Tools/$KINC_PLATFORM"
else
git -C `dirname "$0"` submodule update --init --remote "Tools/$KINC_PLATFORM"
git -C `dirname "$0"`/Tools/$KINC_PLATFORM checkout main
fi