#!/usr/bin/env bash
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	MACHINE_TYPE=`uname -m`
	if [[ "$MACHINE_TYPE" == "armv"* ]]; then
		git -C `dirname "$0"` submodule update --init --remote Tools/linux_x64
	elif [[ "$MACHINE_TYPE" == "aarch64"* ]]; then
		git -C `dirname "$0"` submodule update --init --remote Tools/linux_arm64
	else
		git -C `dirname "$0"` submodule update --init --remote Tools/linux_arm
	fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
	git -C `dirname "$0"` submodule update --init --remote Tools/macos
elif [[ "$OSTYPE" == "FreeBSD"* ]]; then
	git -C `dirname "$0"` submodule update --init --remote Tools/freebsd_x64
fi
