#pragma once

#include <kinc/threads/atomic.h>

#define KORE_ATOMIC_COMPARE_EXCHANGE KINC_ATOMIC_COMPARE_EXCHANGE

#define KORE_ATOMIC_COMPARE_EXCHANGE_POINTER KINC_ATOMIC_COMPARE_EXCHANGE_POINTER

#define KORE_ATOMIC_INCREMENT KINC_ATOMIC_INCREMENT

#define KORE_ATOMIC_DECREMENT KINC_ATOMIC_DECREMENT
